### ISSUE TITLE
Doctrine dbal 3.0 compatiblity

### ISSUE THREAD

**Issue by sdrenth** [BitBagCommerce/SyliusProductAttributeGroupsPlugin#16]
When installing this plugin I ran into a dependency conflict between this package and another package because of doctrine/dbal version conflicts. Sylius 1.12 requires either 2.7 or 3.0, whereas Sylius 1.13 requires 3.0.

Are there any plans to make this package compatible with doctrine/dbal 3.0?

**Update:** 
I did not run into any issues when I cloned the repo locally and removed the conflict section from the composer.json file, everything was working fine when installing the plugin.

**Comment by senghe** [comment]
Hi @sdrenth, we plan to fix the issue with Doctrine DBAL 3.0 with all of our plugins, but I can't tell you any good estimation for the current package.

**Comment by senghe** [comment]
Aaaaah, apologize, I was mentally into different issue (with the ORM). I've just tested application without the conflict and it works fine. It's been just released as v2.0.1.

**Comment by sdrenth** [comment]
@senghe Thank you for the quick fix and release!
